version: "3"

networks:
  main:

services:
  bitbucket:
    build:
      context: ./docker-image-specs/bitbucket
      dockerfile: dockerfile
    # environment: {}
    # volumes:
    #   - "./data/maven:/root/.m2/repository"
    #   - "./data/bitbucket:/amps-standalone-bitbucket-LATEST"
    ports:
    - "7995:7990"
    networks:
      main:
        aliases:
          - bitbucket
