---
connection:
  user: admin
  password: admin
  baseUrl: http://localhost:7995/bitbucket

config:
  users:
    admin: ignore
    user-read: ignore
    user-write: ignore
    user-admin: ignore

  groups: ignore

  projects:
    PROJECT_1: ignore

    PROJECT:
      description: Description for Sample Project
      name: PROJECT
      public: false
      repos:
        new_w_permissions:
          forkable: true
          public: false
          scmId: git
          permissions:
            users: {}
            groups:
              group-read: REPO_READ
              group-write: REPO_WRITE
              group-admin: REPO_ADMIN
        existing_permissions_to_remove:
          forkable: true
          public: false
          scmId: git
          permissions:
            users: {}
            groups: {}
        existing_to_add_permissions:
          forkable: true
          public: false
          scmId: git
          permissions:
            users: {}
            groups:
              group-read: REPO_READ
              group-write: REPO_WRITE
              group-admin: REPO_ADMIN
