---
connection:
  user: admin
  password: admin
  baseUrl: http://localhost:7995/bitbucket

config:
  users:
    admin: ignore
    # change display name
    user1:
      displayName: User1_chg
      email: user1@example.com
      name: user1
      password: user1
    # change email
    user2:
      displayName: User2
      email: user2_chg@example.com
      name: user2
      password: user2
    # change everything
    user3:
      displayName: User3_chg
      email: user3_chg@example.com
      name: user3
      password: user3

  groups:
    stash-users:
      members:
      - admin
      permission: LICENSED_USER

  projects:
    PROJECT_1: ignore
