---
connection:
  user: admin
  password: admin
  baseUrl: http://localhost:7995/bitbucket

config:
  users:
    admin: ignore

  groups:
    stash-users: ignore
    sys-admin-group:
      members:
      - admin
      permission: SYS_ADMIN
    custom-group:
      members:
      - admin

  projects:
    PROJECT_1: ignore
